sudo: required
env:
  global:
    - IMAGE_NAME=nithinbenny444/travis-test
    - IMAGE_TAG="$TRAVIS_BUILD_NUMBER"
services:
  - docker
language: bash
language: node_js
node_js:
  - "node"

install:
  - npm install

before_script:
  - npm test

script:
  - docker build -t "$IMAGE_NAME" .
  - docker tag "$IMAGE_NAME" "$IMAGE_NAME:$IMAGE_TAG"
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push "$IMAGE_NAME:$IMAGE_TAG"
after_script:

  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - sudo apt-get update && sudo apt-get install -y apt-transport-https && 
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && 
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list && 
    sudo apt-get update &&
    sudo apt-get install -y kubectl
  - sudo az login --service-principal -u b7b518ed-9860-4d3e-af5d-d55eccd876aa -p d0e5487d-2dac-4ed0-9425-4a5ff3cb044d --tenant 38a45ae8-5a43-4639-8640-e0104d51d5c2
  - az aks get-credentials --resource-group LendicoDev1 --name dev1 --admin
  - kubectl get nodes