sudo: required
env:
  global:
    - IMAGE_NAME=nithinbenny444/travis-test
    - IMAGE_TAG="$TRAVIS_BUILD_NUMBER"
services:
  - docker
language: bash
language: node_js
node_js:
  - "node"

install:
  - npm install

before_script:
  - npm test

script:
  - docker build -t "$IMAGE_NAME" .
  - docker tag "$IMAGE_NAME" "$IMAGE_NAME:$IMAGE_TAG"

after_script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push "$IMAGE_NAME:$IMAGE_TAG"
  - apt-get install python
  - echo "The image name is $IMAGE_NAME:$IMAGE_TAG"