sudo: required
env:
  global:
    - IMAGE_NAME=nithinbenny444/travis-test
    - IMAGE_TAG="$TRAVIS_BUILD_NUMBER"
    - MANIFEST_DEPLOYMENT_FILE_NAME="sample-nodeapp-k8s.yaml"
services:
  - docker
language: bash
language: node_js
node_js:
  - "node"

install:
  - npm install

before_script:
  - npm test

script:
  - docker build -t "$IMAGE_NAME" .
  - docker tag "$IMAGE_NAME" "$IMAGE_NAME:$IMAGE_TAG"
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push "$IMAGE_NAME:$IMAGE_TAG"
after_script:

  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - sudo az aks install-cli
  - sudo az login --service-principal -u $SVC_PRINCIPAL_ID -p $SVC_PRINCIPAL_PASSWORD --tenant $TENANT_ID
  - sudo az aks get-credentials --resource-group $RESOURCE_GROUP_NAME --name $AKS_CLUSTER --admin
  - sudo kubectl get nodes
  - oldTag=$(cat $MANIFEST_DEPLOYMENT_FILE_NAME | grep -P $IMAGE_NAME | awk -F ":" '{print $3}')
  - oldImage=$IMAG_ENAME:$oldTag
  - newImage=$IMAGENAME:$IMAGE_TAG
  - sed -i "s@$oldImage@$newImage@" $MANIFEST_DEPLOYMENT_FILE_NAME
  - sudo kubectl create -f sample-nodeapp-k8s.yaml
  - echo $IMAGE_TAG
  - echo $TRAVIS_BUILD_NUMBER