sudo: required
env:
  global:
    - IMAGE_NAME=nithinbenny444/travis-test
    - IMAGE_TAG="$TRAVIS_BUILD_NUMBER"
services:
  - docker
language: bash
language: node_js
node_js:
  - "node"

install:
  - npm install

before_script:
  - npm test

script:
  - docker build -t "$IMAGE_NAME" .
  - docker tag "$IMAGE_NAME" "$IMAGE_NAME:$IMAGE_TAG"
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push "$IMAGE_NAME:$IMAGE_TAG"
after_script:

  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - sudo az aks install-cli
  - sudo az login --service-principal -u $SVC_PRINCIPAL_ID -p $SVC_PRINCIPAL_PASSWORD --tenant $TENANT_ID
  - sudo az aks get-credentials --resource-group $RESOURCE_GROUP_NAME --name $AKS_CLUSTER --admin
  - sudo kubectl get nodes