---
apiVersion: v1
kind: Service
metadata:
  name: sample-node
  namespace: dev-test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    component: sample-node
    environment: dev
  type: ClusterIP
                  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev-test
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-cred


