---
apiVersion: v1
kind: Service
metadata:
  name: sample-node
  namespace: dev-test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    component: sample-node
    environment: dev
  type: ClusterIP
                  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node
  namespace: dev-test
  labels:
    app: sample-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-node
  template:
    metadata:
      labels:
        app: sample-node
    spec:
      containers:
      - name: sample-node
        image: nithinbenny444/travis-test:0.14
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-cred


